package IDMConsolePermissions;

dialect 'mvel'

import java.security.Principal;

import org.jboss.seam.security.permission.PermissionCheck;

# Allow all users to read the available roles

rule ReadRoles
  no-loop
  activation-group "permissions"
when
  check: PermissionCheck(resource == "seam.role", permission == "read", granted == false)
//  Role(name == "user")
then
  check.grant();
end

rule CreateAccount
  no-loop
  activation-group "permissions"
when
  check: PermissionCheck(resource == "seam.account", permission == "create", granted == false)
//  Role(name == "admin")
then
  check.grant();
end

/*****************************************************************************************

  The Following Rules are for Identity Management
  
******************************************************************************************/

rule ManageUsers
  no-loop
  activation-group "permissions"
when
  check: PermissionCheck(resource == "seam.identity", granted == false)
then
  check.grant();
end

rule ManageRoles
  no-loop
  activation-group "permissions"
when
  check: PermissionCheck(resource == "seam.role", granted == false)
//  Role(name == "admin")
then
  check.grant();
end
